import { Chess } from './vendor/10-chess.js';
const pieces={wp:'♙',wn:'♘',wb:'♗',wr:'♖',wq:'♕',wk:'♔',bp:'♟',bn:'♞',bb:'♝',br:'♜',bq:'♛',bk:'♚'};
const board=document.querySelector('#board'), status=document.querySelector('#gameStatus'), turnText=document.querySelector('#turnText'), engineState=document.querySelector('#engineState'), thinking=document.querySelector('#thinking'), dot=document.querySelector('#statusDot');
const sideSelect=document.querySelector('#sideSelect'), strengthSelect=document.querySelector('#strengthSelect'), sideLabel=document.querySelector('#sideLabel'), movesEl=document.querySelector('#moves');
let game=new Chess(), orientation='w', player='w', selected=null, legal=[], last=[], busy=true, worker;
const files=['a','b','c','d','e','f','g','h'];
function toast(t){const e=document.querySelector('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function squares(){const ranks=orientation==='w'?[8,7,6,5,4,3,2,1]:[1,2,3,4,5,6,7,8];const fs=orientation==='w'?files:[...files].reverse();return ranks.flatMap(r=>fs.map(f=>f+r))}
function render(){board.innerHTML='';for(const sq of squares()){const f=files.indexOf(sq[0]),r=+sq[1];const p=game.get(sq);const el=document.createElement('button');el.className=`square ${(f+r)%2?'light':'dark'}`;el.dataset.square=sq;el.setAttribute('role','gridcell');el.setAttribute('aria-label',`${sq}${p?' '+(p.color==='w'?'white ':'black ')+p.type:''}`);if(selected===sq)el.classList.add('selected');if(last.includes(sq))el.classList.add('last');const lm=legal.find(m=>m.to===sq);if(lm)el.classList.add(lm.captured?'capture':'legal');if(p){const span=document.createElement('span');span.className=`piece ${p.color==='w'?'white-piece':'black-piece'}`;span.textContent=pieces[p.color+p.type];el.append(span)}const firstFile=orientation==='w'?'a':'h',bottomRank=orientation==='w'?'1':'8';if(sq[0]===firstFile){const c=document.createElement('span');c.className='coord rank';c.textContent=sq[1];el.append(c)}if(sq[1]===bottomRank){const c=document.createElement('span');c.className='coord file';c.textContent=sq[0];el.append(c)}el.onclick=()=>clickSquare(sq);board.append(el)}renderMoves();updateStatus()}
function updateStatus(){let title='Your move',sub=game.turn()==='w'?'White to move':'Black to move';if(game.isCheckmate()){title=game.turn()===player?'Checkmate. Ravager wins.':'Checkmate. You win.';sub='Game over'}else if(game.isDraw()){title='Draw';sub='Game over'}else if(game.inCheck())title='Check';if(busy&&!game.isGameOver()){title=worker?'Ravager is thinking':'Engine loading...';sub='Please wait'}status.textContent=title;turnText.textContent=sub;document.querySelector('#undo').disabled=busy||game.history().length<2}
function clickSquare(sq){if(busy||game.isGameOver()||game.turn()!==player)return;const p=game.get(sq);if(selected){const candidates=legal.filter(m=>m.to===sq);if(candidates.length){if(candidates.some(m=>m.promotion)){showPromotion(selected,sq);return}makePlayerMove({from:selected,to:sq});return}selected=null;legal=[]}if(p&&p.color===player){selected=sq;legal=game.moves({square:sq,verbose:true});}render()}
function showPromotion(from,to){const modal=document.querySelector('#promotion'),box=document.querySelector('#promotionChoices');box.innerHTML='';for(const type of ['q','r','b','n']){const b=document.createElement('button');b.textContent=pieces[player+type];b.onclick=()=>{modal.hidden=true;makePlayerMove({from,to,promotion:type})};box.append(b)}modal.hidden=false}
function makePlayerMove(m){const out=game.move(m);if(!out)return;last=[out.from,out.to];selected=null;legal=[];render();if(!game.isGameOver())requestEngine()}
function requestEngine(){busy=true;thinking.hidden=false;updateStatus();worker.postMessage({type:'move',fen:game.fen(),time:+strengthSelect.value})}
function startWorker(){busy=true;worker=new Worker('./4-engine-worker.js',{type:'module'});worker.onmessage=({data})=>{if(data.type==='ready'){engineState.textContent='NNUE READY · LOCAL';dot.className='dot';busy=false;render();if(game.turn()!==player)requestEngine()}else if(data.type==='move'){if(data.move){const m=game.move({from:data.move.slice(0,2),to:data.move.slice(2,4),promotion:data.move[4]||'q'});if(m)last=[m.from,m.to]}busy=false;thinking.hidden=true;render()}else if(data.type==='error'){engineState.textContent='ENGINE ERROR';dot.className='dot error';busy=false;thinking.hidden=true;status.textContent='Engine failed to load';turnText.textContent=data.message}};worker.onerror=()=>{dot.className='dot error';engineState.textContent='ENGINE ERROR';busy=false;updateStatus()}}
function newGame(){game=new Chess();player=sideSelect.value;orientation=player;sideLabel.textContent=player==='w'?'WHITE':'BLACK';selected=null;legal=[];last=[];render();if(worker&&game.turn()!==player)requestEngine()}
function renderMoves(){const hist=game.history();if(!hist.length){movesEl.innerHTML='<p>No moves yet.</p>';return}let h='';for(let i=0;i<hist.length;i+=2)h+=`<div class="move-row"><span class="move-no">${i/2+1}.</span><span>${hist[i]}</span><span>${hist[i+1]||''}</span></div>`;movesEl.innerHTML=h;movesEl.scrollTop=movesEl.scrollHeight}
document.querySelector('#newGame').onclick=newGame;sideSelect.onchange=newGame;document.querySelector('#flip').onclick=()=>{orientation=orientation==='w'?'b':'w';render()};document.querySelector('#undo').onclick=()=>{if(busy)return;game.undo();game.undo();last=[];selected=null;legal=[];render()};document.querySelector('#copyPgn').onclick=async()=>{await navigator.clipboard.writeText(game.pgn());toast('PGN COPIED')};
render();startWorker();
